### PR TITLE
Adding Astra DB as a dependency 

### PR DESCRIPTION
**Pull request by melienherrera**
## What was changed
Added files and steps on how to connect with Astra DB as a dependency. Included the files that are needed, added it to the chart, and added a section in the README with more steps on how users can configure the setup. 

## Why?
I added these changes so that users can be exposed to new options to use their database with. Temporal and DataStax Astra currently work together, so having a community friendly option and readily available to use is great as well!

1. Closes[ this issue](https://github.com/temporalio/temporal/issues/2419)

2. How was this tested:
This was tested locally with the same template as you would run with docker compose, but using the updated files as the template. Same process as existing - no major changes. 

3. Any docs updates needed?
Updated README.md is already included. 
Could also add this [documentation](https://www.datastax.com/blog/how-to-connect-temporal-io-to-astra-db-in-just-5-easy-steps) to docs.temporal.io[ runbook page](https://docs.temporal.io/docs/server/production-deployment/#external-runbooks)

### CODE REVIEW

**Comment by melienherrera** [comment]
Screen Shot 2022-05-04 at 1 22 44 PM
Hi, its showing this when I try to sign the CLA. Am I missing something?

**Comment by melienherrera** [comment]
Hi there - bumping this PR

**Review by alexshtin — COMMENTED** [review]
I don't understand why don't you use database tools from auto-setup? Why do you want to run it manually?

**Comment by melienherrera** [comment]
> I don't understand why don't you use database tools from auto-setup? Why do you want to run it manually?

Can you elaborate on this? How would we go about this?

**Comment by robholland** [comment]
I'm not convinced we should merge this, I wouldn't expect us to have compose files for every hosted version of each database we support. Users can test temporal with our locally-running cassandra compose files.

**Comment by melienherrera** [comment]
Hi @robholland! The files included include a quick setup for Astra specifically. There are configs created aside from the existing temporal cassandra compose files. Having such Astra-Temporal compatible compose files would be super convenient for this integration. We also have an [article](https://www.datastax.com/blog/how-to-connect-temporal-io-to-astra-db-in-just-5-easy-steps) published that was reviewed by Temporal folks.

**Comment by robholland** [comment]
We don't want to encourage people to use these docker compose setups for production, they are intended only for local development and experimenting. Also we can't easily maintain or test these files as the system is not self-contained.

The article you refer to references a third party repository which includes an Astra setup for docker-compose.

**Comment by robholland** [comment]
For anyone landing on this PR, please note that it is possible to connect to Astra without this extra infrastructure, see https://github.com/temporalio/temporal/issues/2419 for details.

**Pull request closed without merging**
